### ISSUE TITLE
Primo UI user experience

### ISSUE THREAD

**Issue by revgum** [osulp/kiosks#159]
When signing into Primo as its visible on the kiosk, the login process eventually takes over and loads Primo as the page in the browser window. 

Maybe we should try and hide and/or prevent clicking the signin button when primo is used in conjunction with the Kiosk UI

**Comment by luisgreg99** [comment]
@revgum we could disable top navigation behavior in the iframe element and use css to hide the login link.

We could have something like this, using the sandbox property in the iframe to set a specific behavior, like disabling top navigation (allows the document to break out of the frame by navigating the top-level window, see https://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/):

```
diff --git a/app/assets/javascripts/react/components/presentational/Touch/SearchPrimo.js b/app/assets/javascripts/react/components/presentational/Touch/SearchPrimo.js
index 370649e..1bd93af 100644
--- a/app/assets/javascripts/react/components/presentational/Touch/SearchPrimo.js
+++ b/app/assets/javascripts/react/components/presentational/Touch/SearchPrimo.js
@@ -5,7 +5,7 @@ var Iframe = React.createClass({
     render: function() {
         return(
             <div>
-                <iframe src={this.props.src} height={this.props.height} width={this.props.width} frameBorder={0} />
+                <iframe src={this.props.src} height={this.props.height} width={this.props.width} frameBorder={0} sandbox={"allow-same-origin allow-scripts allow-popups allow-forms"} />
             </div>
         )
     }
```
This patch above would restricts the iframe with the following behavior:

- `allow-popups` allows popups (window.open(), showModalDialog(), target=”_blank”, etc.).
- `allow-same-origin` allows the document to maintain its origin; pages loaded from https://example.com/ will retain access to that origin’s data.
- `allow-scripts` allows JavaScript execution, and also allows features to trigger automatically (as they’d be trivial to implement via JavaScript).
- `allow-forms` allows form submission.

Then we can hide the login with css within the iframe.

**Comment by revgum** [comment]
solved by Dan with a new primo view
