### ISSUE TITLE
Filtering classrooms excludes; tapping a classroom should exclude all and include only what user selects

### ISSUE THREAD

**Issue by dmoore** [osulp/kiosks#186]
Currently, when a user is looking at the classroom schedule, they can tap the classroom name. A user might expect this action to exclude all the other classrooms and include only the classroom they tapped. However, this is not the behavior. Instead, it excludes the classroom the user tapped. This is contrary to the expected behavior I think most users will anticipate.

**Comment by luisgreg99** [comment]
fixed by https://github.com/osulp/kiosks/pull/202
