### ISSUE TITLE
allow use of SRT and/or DFXP files for captioning

### ISSUE THREAD

**Issue by vantuyls** [osulp/kiosks#196]
Mediaspace allows captioning using only the SRT and DFXP formats. Some of the media that will be used in the Media Kiosk application will need to also be hosted (and captioned) on Mediaspace, so it would be easiest if we only had to build *one* caption file.

**Comment by vantuyls** [comment]
it's possible that SRT and VTT (is that the name of the current captioning file format?) are the same?

https://www.3playmedia.com/2017/03/08/create-srt-file/

**Comment by straleyb** [comment]
Captioning has been completed.
