### ISSUE TITLE
add in tab and scope selector to new Primo search bar

### ISSUE THREAD

**Issue by dmoore** [osulp/kiosks#205]
The library's website uses the following script to allow students to pre-select tabs before they execute their search query: https://github.com/osulp/OSUL-Website/blob/23ea50b6ceddbe1dda1c5a0deaec4e08ad7f0241/sites/all/themes/doug-fir-d7-library/primo_search.js

Since we're using a Kiosk search bar and have hidden the Primo search bar (which actually has the selectors for tabs and scopes), we'll need to add a similar tab and scope selector with the following values: 

- 1Search - Print Only tab with Valley Library Materials scope = `tab=default_tab&search_scope=osu_print`
- 1Search - Print Only tab with SCARC scope = `tab=default_tab&search_scope=osu_scarc`
- Course Reserves tab with OSU Course Reserves scope = `tab=cr_tab&search_scope=osu_cr`
- Course Reserves tab with HSRC scope = `tab=cr_tab&search_scope=HSRC%20Textbook%20Lending%20Library`

**Comment by straleyb** [comment]
1search is integrated.
