### ISSUE TITLE
new donor kiosk layout

### ISSUE THREAD

**Issue by luisgreg99** [osulp/kiosks#247]
### Descriptive summary

Create new donor layout and make the design match the library website version.

Deadline: June 2019

- [x] get layout designs from Don
- [ ] implement new layout based on the designs provided

Resources:

[Donor Kiosk Project](https://oregonstate.app.box.com/link/?lp=qxWhYYgx9J7uuD2fDV0W13czUgBqHPUSQ8YFvlqDuc20fhwu_q857NI-wdgxuWvgMj9m2khzET4Ym9OgY5xRNxu74W5yeySpbs5Xj6sSzVksxtmHxpStvxV4Q4iZrsbx1abGx1OdO-ypXa_VS9cdHSqbn_nuxypX-S1O8GvP8qqiovzSa7dwQWKItUOP9yujN1xqfzFPhNJ2zPUMusfU7yn-YLLashpC3m53Z6SMsKkDNrxg48K0frGOFX4eMdMxv9mrX64wSFCoe72NrcJsO07UgUILSfOesYjeBZlGk_oe-ZYb76w9nbxM9aCcl4_-MIl4Fd_1q2kXsA4Y5hNU6deFYXjpSK0pu25Z6qargyc_b6DQPiqzoo4XA_qYvsdscYrtSxeHEQEnT9SrkPHO6kCWkqX0Xz4.&a=click&tt=ItemLink&ru=Kyh6UXv7tK78_iKnlBaJIq8MS1Mcjs3UVn-5G45_jWRFr8yIc9_ljfxlzSWTjQmbK5KzLt4tdVUNj8HviGSrA7xE7EaDIBV8_u0Y34OyO5F82dCdMvsuNXfY1pYBg1_6wMStXb2TaH1bFxXWs-MNNv93WQFg8BMM6wjXezV1I_SLDd98C7KStGlKmlGWpLq9iXSrklu--pia8vwZMcCELhemRoudMLE0nHuFuHcHJZIQW7UEOS1HlWPlA10nEEkMm1o.)

**Comment by revgum** [comment]
![20181018_104745](https://user-images.githubusercontent.com/32885/47176798-5de0ae80-d2cb-11e8-9f21-9672f0c252e9.jpg)

**Comment by vantuyls** [comment]
cover flow should rotate on a timer to prevent the image from being static.

**Comment by vantuyls** [comment]
should have a single representation image for each cover in the cover flow.
