### ISSUE TITLE
fix encoding for some images causing brightsign hardware to crash

### ISSUE THREAD

**Issue by revgum** [osulp/kiosks#256]
the background image, and some of the images in cells seem to have bad encoding that causes the brightsign hardware to crash. I'm not sure what/how to change their encoding, but it needs to be done to complete testing.

![screenshot 2018-12-06 16 41 15](https://user-images.githubusercontent.com/32885/50712659-24e0ec00-1027-11e9-9f91-d8b107d4edea.png)

**Comment by straleyb** [comment]
Donor kiosk layout not used anymore. Outdated.
