### ISSUE TITLE
Available study rooms counter not very effective

### ISSUE THREAD

**Issue by luisgreg99** [osulp/kiosks#259]
### Descriptive summary
From asana ticket:

> The counter for available study rooms is not very effective. Originally it tallied only rooms available for at least an hour. Now it tallies every room, even those with only a 10 minute window. Additionally, the update cycle is nearly 5 minutes. This makes the tally even less accurate since it may show 3 rooms available when there are none. 

### Actual behavior

Study Rooms Available doesn't display an accurate count.
![image](https://user-images.githubusercontent.com/3486120/52513767-d690b100-2bc1-11e9-9e41-05e3ec5843e7.png)

### Expected behavior
From asana ticket:
> It would be nice to have a tally that only shows rooms available for at least an hour and updates every minute. If that is not possible, then we should probably remove the tally entirely because it is not effective anymore. Thanks.

### Related work:
https://github.com/osulp/kiosks/pull/144

Dev Notes:

I think we can tweak https://github.com/osulp/kiosks/blob/master/app/controllers/api/v1/rooms_controller.rb#L6 to display available rooms counter for at least an hour and then update the timer at https://github.com/osulp/kiosks/blob/master/app/assets/javascripts/react/components/presentational/Circulation/Kiosk.js#L38 to update every minute instead of 10min (default)

**Comment by straleyb** [comment]
Disabled.
