### ISSUE TITLE
Production deploy node module missmatch

### ISSUE THREAD

**Issue by straleyb** [osulp/kiosks#261]
Node version was mismatched, when switched to a newer version, cap was mismatched. Dig in to figure out why production deploy isnt working. Staging is working properly. Could use the versions from there to get production working.

**Comment by revgum** [comment]
Kiosks was updated to use Ruby 2.5.1, but the deployment configuration was still forcing 2.3.3 in the command

**Comment by revgum** [comment]
Yarn needed to be installed for the latest node version on the server as well `npm install -g yarn`
