### ISSUE TITLE
Alert shows after using CAS to log in

### ISSUE THREAD

**Issue by mellinma** [osulp/kiosks#296]
![Screen Shot 2019-03-08 at 3 22 35 PM](https://user-images.githubusercontent.com/11778515/54061534-24470c00-41b6-11e9-9d83-7bb9e193e715.png)

I successfully logged in to http://kiosks.library.oregonstate.edu/ with my ONID credentials and DUO.  I got this alert "You need to sign in or sign up before continuing."  But I *could* continue.

**Comment by straleyb** [comment]
I wasnt able to reproduce this error.

**Comment by straleyb** [comment]
![onid_kiosk_login](https://user-images.githubusercontent.com/6424683/54061931-fd89d500-41b7-11e9-907b-37008e929059.gif)

**Comment by mellinma** [comment]
I also could not reproduce it in Safari, Firefox or Chrome.  It happened to me in Firefox at first.  I'm closing this ticket.
