### ISSUE TITLE
Logged in Name display differences 

### ISSUE THREAD

**Issue by mellinma** [osulp/kiosks#297]
![Screen Shot 2019-03-08 at 3 31 07 PM](https://user-images.githubusercontent.com/11778515/54061802-59079300-41b7-11e9-8334-0c43e990a7d1.png)
![Screen Shot 2019-03-08 at 3 31 19 PM](https://user-images.githubusercontent.com/11778515/54061803-59a02980-41b7-11e9-9f69-d934f71e0660.png)

Logged in with ONID - showing ONID name (mellinma)  on Home, Showing email on Admin panel (margaret.mellinger@oregonstate.edu)   
This is just an oddity,  it doesn't seem to affect performance in any way

**Comment by straleyb** [comment]
Should we prefer the email on the display or the username? Easy fix, but just need to make a decision.

**Comment by mellinma** [comment]
I think username - shorter

**Comment by straleyb** [comment]
Ahh I see whats going on. Honestly, that part of the application is managed through rails admin, and may be a bit more challenging to switch.

**Comment by straleyb** [comment]
@revgum @luisgreg99 How much is the rails_admin portion of the application used anymore?

**Comment by straleyb** [comment]
https://github.com/sferik/rails_admin/blob/master/app/helpers/rails_admin/application_helper.rb#L41

Here is the line of code that generates the link. We could override it and change it to use the username instead but that seems smelly

**Comment by straleyb** [comment]
Fixed by #298
