### ISSUE TITLE
short videos on the kiosks

### ISSUE THREAD

**Issue by luisgreg99** [osulp/kiosks#370]
From Beth:

> filarwilliams  11:50 AM
... we can do short videos on the kiosks? Im imaginging a boomarang type video on instagram? the MU Creative Studio who does some of our slides for kiosks says they can do little videos and put on the kiosks in MU and Dixon etc --- 

Related:
Asana ticket: https://app.asana.com/0/299373448889415/1164206399999206

**Comment by CGillen** [comment]
Dave mentioned gifs as an alternative if we can't update kiosks to support videos. The assumption here being that we have to keep an `<img>` tag. An alternative to gif, webp, can produce better quality (32-bit color vs 8-bit) at less filesize, either lossy or lossless.

Video will probably still be better, but if we're stuck with `<img>`, checkout webp.

**Comment by luisgreg99** [comment]
It turns out that [react-image-gallery](https://github.com/xiaolin/react-image-gallery) (used for the slides component) actually supports gif files, so we ended up adding slides with this file type for now. It's probably worth checking out webp for custom gifs.

**Comment by luisgreg99** [comment]
Fixed by https://github.com/osulp/kiosks/pull/399 SlideGallery base component now supports video content in the slide element (the source can be defined in the `av_media` field).
