### ISSUE TITLE
[Admin Kiosk]Fit entire kiosk screen to fit without scrolling in 1920 x 1080

### ISSUE THREAD

**Issue by straleyb** [osulp/kiosks#423]
Currently you have to scroll down a little bit in order to see the whole button list at the bottom. This needs to be mended so the whole screen is filled properly without the need to scroll.

**Comment by luisgreg99** [comment]
fixed by https://github.com/osulp/kiosks/pull/427 and https://github.com/osulp/kiosks/pull/429
